@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
}

val generatedFirebaseDir = layout.buildDirectory.dir("generated/firebase")

val generateFirebaseConfig by tasks.registering {
    description = "Writes GeneratedFirebaseConfig.kt from env vars or desktopApp/local.properties"
    outputs.dir(generatedFirebaseDir)

    doLast {
        val outDir = generatedFirebaseDir.get().asFile
        outDir.mkdirs()

        fun escape(value: String): String =
            value.replace("\\", "\\\\").replace("\"", "\\\"")

        var apiKey = System.getenv("IMUFLUX_FIREBASE_API_KEY")?.trim().orEmpty()
        var projectId = System.getenv("IMUFLUX_FIREBASE_PROJECT_ID")?.trim().orEmpty()
        var source = "environment variables"

        if (apiKey.isEmpty() || projectId.isEmpty()) {
            val localProps = rootProject.file("desktopApp/local.properties")
            if (localProps.exists()) {
                val props = Properties()
                localProps.inputStream().use(props::load)
                val fileApiKey = props.getProperty("firebase.apiKey")?.trim().orEmpty()
                val fileProjectId = props.getProperty("firebase.projectId")?.trim().orEmpty()
                if (fileApiKey.isNotEmpty() && fileProjectId.isNotEmpty()) {
                    apiKey = fileApiKey
                    projectId = fileProjectId
                    source = "desktopApp/local.properties"
                }
            }
        }

        if (apiKey.isEmpty() || projectId.isEmpty()) {
            apiKey = ""
            projectId = ""
            source = "unset"
        }

        val content = """
            package com.sarmidev.imuflux.web

            /** Generated by the generateFirebaseConfig Gradle task — do not edit. */
            object GeneratedFirebaseConfig {
                const val apiKey: String = "${escape(apiKey)}"
                const val projectId: String = "${escape(projectId)}"
                const val source: String = "${escape(source)}"
            }
        """.trimIndent() + "\n"

        outDir.resolve("GeneratedFirebaseConfig.kt").writeText(content)
    }
}

kotlin {
    wasmJs {
        outputModuleName.set("imufluxBackoffice")
        browser()
        binaries.executable()
    }

    sourceSets {
        wasmJsMain {
            kotlin.srcDir(generatedFirebaseDir)
            dependencies {
                implementation(project(":backofficeCore"))
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
            }
        }
    }
}

tasks.named("compileKotlinWasmJs") {
    dependsOn(generateFirebaseConfig)
}
